// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2lcvOSxoUDXky1EZW3fGhnQw-MbQGeGw',
    appId: '1:652993173782:web:6f3e7eb1c40f58b36a5837',
    messagingSenderId: '652993173782',
    projectId: 'entangl-c11b2',
    authDomain: 'entangl-c11b2.firebaseapp.com',
    storageBucket: 'entangl-c11b2.firebasestorage.app',
    measurementId: 'G-CHYZ1N382S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBwAUTiK46l4NOe9Lt162LePpOadXFK8',
    appId: '1:652993173782:android:4254e53f4358c50e6a5837',
    messagingSenderId: '652993173782',
    projectId: 'entangl-c11b2',
    storageBucket: 'entangl-c11b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qBj6iQe1nxyTXb7Lbiz8elDhBvi_yYE',
    appId: '1:652993173782:ios:ee32db067179de096a5837',
    messagingSenderId: '652993173782',
    projectId: 'entangl-c11b2',
    storageBucket: 'entangl-c11b2.firebasestorage.app',
    iosBundleId: 'com.entangl.entanglApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4qBj6iQe1nxyTXb7Lbiz8elDhBvi_yYE',
    appId: '1:652993173782:ios:ee32db067179de096a5837',
    messagingSenderId: '652993173782',
    projectId: 'entangl-c11b2',
    storageBucket: 'entangl-c11b2.firebasestorage.app',
    iosBundleId: 'com.entangl.entanglApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2lcvOSxoUDXky1EZW3fGhnQw-MbQGeGw',
    appId: '1:652993173782:web:fd07227a725188b56a5837',
    messagingSenderId: '652993173782',
    projectId: 'entangl-c11b2',
    authDomain: 'entangl-c11b2.firebaseapp.com',
    storageBucket: 'entangl-c11b2.firebasestorage.app',
    measurementId: 'G-ZY8HK4WTXV',
  );
}
